env:
  browser: true
  commonjs: true
  es6: true
  jest: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  angular: xpto
  inject: 1
  sforce: 1
parserOptions:
  ecmaVersion: 2018
  ecmaFeatures:
    impliedStrict: true
rules: {
  curly: [2, 'all'],
  func-names: 0, # off, doesn't play well with AngularJS
  indent: [2, "tab", { SwitchCase: 1 }], # error, enforce tabs only
  max-len: 0, # off
  no-param-reassign: [2, { props: false} ], # error, don't error on param props change
  no-plusplus: [2, { allowForLoopAfterthoughts: true }], # error, allow plus-plus only in loop afterthoughts
  no-tabs: 0, # off
  no-use-before-define: [2, { functions: false }], # off since we mainly using function declarations which are always hoisted
  prefer-arrow-callback: 0, # off, doesn't play well with AngularJS
  radix: 0, # off
  space-before-function-paren: [2, "never"], #never allow spaces after
  vars-on-top: 0, # off, don't allow use of var in general since they are error-prone
  no-cond-assign: [2, "except-parens" ],
  no-console: 0,
}