#SwiftLint: https://github.com/realm/SwiftLint
#Rules: https://github.com/realm/SwiftLint/blob/master/Rules.md

#supports autocorrection - SA
#no – team decision not to include a rule.

reporter: "xcode"

excluded:
  - .build
  - DerivedData
  - "*/.build"
  - "*/DerivedData"
  - Frameworks/CocoaMarkdown
  - Frameworks/ObjCTools
  - Frameworks/OCMock.framework
  - Frameworks/RHAdditions
  - Frameworks/SetappAnalytics
  - Templates
  - Scripts
  - "*/Templates"
  - "*/Scripts"
  - SetappInstaller/Scripts
  - SetappAgent/Scripts
  - XCUITestRunner
  - TestingService
  - LocalizationHelper
  - SetappFeatureFlags/Tests/SetappFeatureFlagsTests
  - "**/Package2.swift"
  - "*.generated.swift"

opt_in_rules: # Enabled rules are uncommented, and disabled are commented.
  # - anonymous_argument_in_multiline_closure
  - anyobject_protocol                              # SA: YES
  - array_init
  # - attributes #no
  # - balanced_xctest_lifecycle
  # - capture_variable
  # - closure_body_length
  # - closure_end_indentation #conflicts            # SA: YES #no - hard
  - closure_spacing                                 # SA: YES
  # - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil                     # SA: YES
  - contains_over_range_nil_comparison
  - convenience_type
  # - discarded_notification_center_observer
  # - discouraged_assert
  # - discouraged_none_name
  # - discouraged_object_literal #no
  - discouraged_optional_boolean                    # SA: YES
  # - discouraged_optional_collection
  # - empty_collection_literal
  - empty_count
  # - empty_string
  # - empty_xctest_method
  # - enum_case_associated_values_count
  # - expiring_todo
  # - explicit_acl #no
  # - explicit_enum_raw_value #no
  - explicit_init                                   # SA: YES
  # - explicit_self                                 # SA: YES
  # - explicit_top_level_acl #no
  # - explicit_type_interface #no
  # - extension_access_modifier #no
  # - fallthrough
  - fatal_error_message
  # - file_header #no
  # - file_name
  # - file_name_no_space
  # - file_types_order
  - first_where
  # - flatmap_over_map_reduce
  - force_unwrapping
  # - function_default_parameter_at_end
  # - ibinspectable_in_extension
  # - identical_operands
  # - implicitly_unwrapped_optional #no
  # - indentation_width
  # - joined_default_parameter
  # - last_where
  # - legacy_multiple
  # - legacy_objc_type
  # - legacy_random
  # - let_var_whitespace
  - literal_expression_end_indentation
  # - lower_acl_than_parent
  # - missing_docs
  # - modifier_order                                # SA: YES
  - multiline_arguments
  # - multiline_arguments_brackets
  # - multiline_function_chains
  # - multiline_literal_brackets
  - multiline_parameters
  # - multiline_parameters_brackets
  - nimble_operator                                 # SA: YES
  # - no_extension_access_modifier
  # - no_grouping_extension #no
  # - nslocalizedstring_key
  # - nslocalizedstring_require_bundle
  # - number_separator #no                          # SA: YES
  # - object_literal #no
  - operator_usage_whitespace                       # SA: YES
  # - optional_enum_case_matching                   # SA: YES
  - overridden_super_call
  - override_in_extension
  # - pattern_matching_keywords
  # - prefer_nimble
  # - prefer_self_in_static_references              # SA: YES
  # - prefer_self_type_over_type_of_self            # SA: YES
  # - prefer_zero_over_explicit_init                # SA: YES
  - prefixed_toplevel_constant
  # - private_action #no
  # - private_outlet #no
  # - private_subject
  # - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  # - raw_value_for_camel_cased_codable_enum
  # - reduce_into
  - redundant_nil_coalescing                        # SA: YES
  # - redundant_type_annotation                     # SA: YES
  # - required_deinit
  - required_enum_case
  # - single_test_class
  - sorted_first_last
  # - sorted_imports #no                            # SA: YES
  - static_operator
  # - strict_fileprivate  #not now
  # - strong_iboutlet                               # SA: YES
  - switch_case_on_newline
  # - test_case_accessibility
  # - toggle_bool                                   # SA: YES
  # - trailing_closure
  # - type_contents_order
  # - unavailable_function
  - unneeded_parentheses_in_closure_argument        # SA: YES
  # - unowned_variable_capture
  # - untyped_error_in_catch
  # - unused_declaration
  # - unused_import                                 # SA: YES
  - vertical_parameter_alignment_on_call
  # - vertical_whitespace_between_cases             # SA: YES
  # - vertical_whitespace_closing_braces            # SA: YES
  # - vertical_whitespace_opening_braces            # SA: YES
  # - xct_specific_matcher
  - yoda_condition

disabled_rules: # Enabled rules are commented, and disabled are uncommented.
  # - block_based_kvo
  # - class_delegate_protocol
  # - closing_brace                                 # SA: YES
  - closure_parameter_position
  # - colon                                         # SA: YES
  # - comma                                         # SA: YES
  # - comment_spacing                               # SA: YES
  # - compiler_protocol_init
  # - computed_accessors_order
  # - control_statement                             # SA: YES
  - custom_rules
  # - cyclomatic_complexity
  # - deployment_target
  # - discouraged_direct_init
  # - duplicate_enum_cases
  # - duplicate_imports
  # - duplicated_key_in_dictionary_literal
  # - dynamic_inline
  # - empty_enum_arguments                          # SA: YES
  # - empty_parameters                              # SA: YES
  # - empty_parentheses_with_trailing_closure       # SA: YES
  - file_length  ##maybe in future
  # - for_where
  # - force_cast
  # - force_try
  # - function_body_length
  # - function_parameter_count
  # - generic_type_name
  - identifier_name
  # - implicit_getter
  - implicit_return  #no                            # SA: YES
  # - inclusive_language
  # - inert_defer
  # - is_disjoint
  # - large_tuple
  # - leading_whitespace                            # SA: YES
  # - legacy_cggeometry_functions                   # SA: YES
  # - legacy_constant                               # SA: YES
  # - legacy_constructor                            # SA: YES
  # - legacy_hashing                                # SA: YES
  # - legacy_nsgeometry_functions                   # SA: YES
  - line_length  #warning #hard #maybe in future
  # - mark                                          # SA: YES
  # - multiple_closures_with_trailing_closure
  # - nesting
  # - no_fallthrough_only
  # - no_space_in_method_call                       # SA: YES
  # - notification_center_detachment
  # - nsobject_prefer_isequal
  - opening_brace
  # - operator_whitespace
  # - orphaned_doc_comment
  # - private_over_fileprivate                      # SA: YES
  # - private_unit_test
  # - protocol_property_accessors_order             # SA: YES
  # - reduce_boolean
  # - redundant_discardable_let                     # SA: YES
  # - redundant_objc_attribute                      # SA: YES
  # - redundant_optional_initialization             # SA: YES
  # - redundant_set_access_control
  # - redundant_string_enum_value
  # - redundant_void_return                         # SA: YES
  # - return_arrow_whitespace                       # SA: YES
  # - self_in_property_initialization
  # - shorthand_operator
  # - statement_position                            # SA: YES
  # - superfluous_disable_command
  # - switch_case_alignment
  # - syntactic_sugar                               # SA: YES
  # - todo
  # - trailing_comma                                # SA: YES
  # - trailing_newline                              # SA: YES
  # - trailing_semicolon                            # SA: YES
  - trailing_whitespace #no                         # SA: YES
  - type_body_length #maybe in future
  # - type_name
  # - unneeded_break_in_switch
  # - unused_capture_list
  # - unused_closure_parameter                      # SA: YES
  # - unused_control_flow_label                     # SA: YES
  # - unused_enumerated
  # - unused_optional_binding
  # - unused_setter_value
  # - valid_ibinspectable
  # - vertical_parameter_alignment
  # - vertical_whitespace                           # SA: YES
  - void_function_in_ternary
  # - void_return                                   # SA: YES
  - weak_delegate
  - xctfail_message

force_cast: warning
empty_count:
  severity: warning

type_name:
  min_length: 3
  max_length: 50
  excluded: Transformer #currently not working

identifier_name:
  min_length: 1
  max_length: 40
  excluded:
    - XCUIElement
    - menuBar

large_tuple:
  warning: 2

conditional_returns_on_newline:
  if_only: true

overridden_super_call:
  included:
    - "awakeFromNib()"
    - "invalidateLayout()"
    - "invalidateLayout(with:)"
    - "layout()"
    - "prepare()"
    - "prepareForReuse()"
    - "updateConstraints()"
    - "viewDidAppear()"
    - "viewDidChangeBackingProperties()"
    - "viewDidDisappear()"
    - "viewDidLayout()"
    - "viewDidLoad()"
    - "viewWillAppear()"
    - "viewWillDisappear()"
    - "viewWillLayout()"
    - "resetCursorRects()"
    - "setUp()"
    - "tearDown()"
    - "updateTrackingAreas()"
    - "windowDidLoad()"
    - "windowWillLoad()"

nesting:
  type_level: 3
  function_level: 2