name: cli-action

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git Version
        id: version
        uses: codacy/git-version@2.2.0
        with:
          prefix: v
          release-branch: main
          dev-branch: feature/**
      - name: New Version
        run: echo ${{ steps.get-version.outputs.version }}
