name: test coverage codacy

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: send coverage
        working-directory: ${{ github.workspace }}
        run: bash ./get.sh report -r src.lcov --t 78973d94455e4f149990dea6ed3b4c13
